### ISSUE TITLE
Available Datasets

### ISSUE THREAD

**Issue by memrekus** [CRI-iAtlas/iatlas-notebooks#8]
Hello there, I'm working on tumor immunology and bioinformatics. Is it possible to reach your processed ICI datasets? If you inform me I would be grateful.

**Comment by Gibbsdavidl** [comment]
Hello!  All of the data is available in our synapse portal:  https://www.synapse.org/#!Synapse:syn10337516/files/

I believe you will find all the ICI data sets under "[Molecular Response to Immune Checkpoint Inhibitors](https://www.synapse.org/#!Synapse:syn24200710)".

**Comment by heimannch** [comment]
@memrekus we also provide an R notebook (https://github.com/CRI-iAtlas/iatlas-notebooks/blob/main/ici_query_iatlas_data.ipynb) and a Python notebook (https://github.com/CRI-iAtlas/iatlas-notebooks/blob/main/ici_query_iatlas_data_python.ipynb) that describes how to access and explore the ICI datasets in CRI iAtlas.
